#!/usr/bin/env bash
# Build the JS/WASM artifact with TinyGo and copy the matching wasm_exec.js.
#
# TinyGo (not standard Go) is used because standard Go bakes its whole runtime
# + GC into every wasm binary (~2.6 MB gz floor). TinyGo drops that, landing
# around 376 KB raw / 156 KB gz. The asyncify scheduler keeps goroutines so the
# fetch-based transport (internal/api/client_tinygo.go) can await responses.
#
# Kept as a standalone script (not a Makefile target) so the upstream Makefile
# stays byte-for-byte identical and `git merge upstream` never conflicts on it.
#
# Usage: ./wasm/build.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

if ! command -v tinygo >/dev/null 2>&1; then
  echo "error: tinygo not found on PATH. Install it: https://tinygo.org/getting-started/install/" >&2
  echo "  macOS: brew tap tinygo-org/tools && brew install tinygo" >&2
  exit 1
fi

VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
COMMIT="$(git rev-parse --short=12 HEAD 2>/dev/null || echo "")"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

OUT="$SCRIPT_DIR/brightlocal.wasm"

# TinyGo silently ignores -ldflags "-X", so stamp build info via a generated
# file (gitignored) instead. main.go declares the defaults; this overrides them.
GEN="$ROOT/cmd/wasm/buildinfo_gen.go"
cat > "$GEN" <<EOF
//go:build js && wasm

// Code generated by wasm/build.sh. DO NOT EDIT.
package main

func init() {
	buildVersion = "${VERSION}"
	buildCommit = "${COMMIT}"
	buildDate = "${DATE}"
}
EOF

echo "building $OUT with tinygo ..."
tinygo build \
  -o "$OUT" \
  -target=wasm \
  -opt=z \
  -no-debug \
  -panic=trap \
  -scheduler=asyncify \
  -gc=conservative \
  ./cmd/wasm

# Optional extra shrink if binaryen's wasm-opt is available.
if command -v wasm-opt >/dev/null 2>&1; then
  echo "optimizing with wasm-opt ..."
  wasm-opt -Oz \
    --enable-bulk-memory --enable-nontrapping-float-to-int \
    --enable-sign-ext --enable-mutable-globals --enable-reference-types \
    --strip-debug "$OUT" -o "$OUT"
fi

# wasm_exec.js must match the TinyGo toolchain that built the wasm. Patch it to
# be Cloudflare Workers / bundler safe (strips Node-only paths esbuild chokes on).
install -m 644 "$(tinygo env TINYGOROOT)/targets/wasm_exec.js" "$SCRIPT_DIR/wasm_exec.js"
node "$SCRIPT_DIR/patch-wasm-exec.mjs" "$SCRIPT_DIR/wasm_exec.js"

RAW="$(du -h "$OUT" | cut -f1 | tr -d ' ')"
GZ="$(gzip -9c "$OUT" | wc -c | awk '{printf "%.0f KB", $1/1024}')"
echo "done: ${RAW} raw / ${GZ} gz (version ${VERSION})"
